<?php
/**
 * Description of Error
 * 
 * This class is an extension of the controller class
 * This class will handle all errors generated by the pages
 *
 * @author Dennis Kuijpers
 * @copyright (c) 2014, Dennis Kuijpers
 * 
 */
class Error extends Controller{
    
    /**
     *  function __construct will automatically generate when method is called
     */
 
    function __construct(){
        parent::__construct(); // Insert __construct method from Class controller
            
                //Debug::sentence("error controller");  
            
                
                $this->view->render('error/index');
        
    }
    
    /**
     *  index()
     * 
     *  - render        The page to be rendered on the website
     *
     */
    
    public function index(){
          $this->view->render('error/index'); 
    }
    
    
    public function er404($data){
        echo $data;
    }
    /**
     * 
     * @todo Aanmaken van een report systeem waardoor de gegevens in de database terecht gaan komen
     */
    public function report($data){
        echo "hier moet een report systeem komen";
    }
}